apiVersion: v1
kind: EcosystemResource
metadata:
  name: Local-Neo4j
spec:
  fqn: Hume.Orchestra.Resource.Neo4j
  parameters:
    - name: host
      value: neo4j
    - name: port
      value: 7687
    - name: user
      value: neo4j
    - name: password
      value: password
    - name: database
      value: chinook