apiVersion: v1
kind: Workflow
metadata:
  name: workflow-test-basic
spec:
  label: 'Workflow Neo4j Basic'
  components:
    - name: Neo4j Reader
      type: "#Hume.Orchestra.DataSource.Neo4jReader"
      config:
        query: MATCH (n:Person) RETURN n
      resource:
        selector:
          name: Local-Neo4j
      to:
        - MessageTransformer
    - name: MessageTransformer
      type: "#Hume.Orchestra.Processor.MessageTransformer"
      config:
        transformer_script: |
          body['source'] = 'neo4j-movies'

          return body
      to:
        - Observer
    - name: Observer
      type: "#Hume.Orchestra.Monitor.Observer"
